"""add_verification_and_onboarding_fields

Revision ID: 36f68e71c11e
Revises: 6840b148d0a7
Create Date: 2026-09-10 14:39:18.864509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f68e71c11e'
down_revision: Union[str, Sequence[str], None] = '6840b148d0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('verification_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('target_weekly_hours', sa.Integer(), server_default='10', nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'target_weekly_hours')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'verification_otp')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
